[package]
name = "url-py"
version = "0.19.0"
edition = "2021"

[lib]
name = "url"
crate-type = ["cdylib"]

[dependencies]
url = "2"

[dependencies.pyo3]
version = "0.28.0"
features = ["extension-module", "generate-import-lib"]
